package com.doran.hardware;
import java.util.HashMap;

public class YoloClassMap {
    public String className(int num) {
        // 클래스 ID와 이름을 매핑할 HashMap
        HashMap<Integer, String> classMap = new HashMap<>();
        classMap.put(0, "person");
        classMap.put(1, "bicycle");
        classMap.put(2, "car");
        classMap.put(3, "motorcycle");
        classMap.put(4, "airplane");
        classMap.put(5, "bus");
        classMap.put(6, "train");
        classMap.put(7, "truck");
        classMap.put(8, "boat");
        classMap.put(9, "traffic light");
        classMap.put(10, "fire hydrant");
        classMap.put(11, "stop sign");
        classMap.put(12, "parking meter");
        classMap.put(13, "bench");
        classMap.put(14, "bird");
        classMap.put(15, "cat");
        classMap.put(16, "dog");
        classMap.put(17, "horse");
        classMap.put(18, "sheep");
        classMap.put(19, "cow");
        classMap.put(20, "elephant");
        classMap.put(21, "bear");
        classMap.put(22, "zebra");
        classMap.put(23, "giraffe");
        classMap.put(24, "backpack");
        classMap.put(25, "umbrella");
        classMap.put(26, "handbag");
        classMap.put(27, "tie");
        classMap.put(28, "suitcase");
        classMap.put(29, "frisbee");
        classMap.put(30, "skis");
        classMap.put(31, "snowboard");
        classMap.put(32, "sports ball");
        classMap.put(33, "kite");
        classMap.put(34, "baseball bat");
        classMap.put(35, "baseball glove");
        classMap.put(36, "skateboard");
        classMap.put(37, "surfboard");
        classMap.put(38, "tennis racket");
        classMap.put(39, "bottle");
        classMap.put(40, "wine glass");
        classMap.put(41, "cup");
        classMap.put(42, "fork");
        classMap.put(43, "knife");
        classMap.put(44, "spoon");
        classMap.put(45, "bowl");
        classMap.put(46, "banana");
        classMap.put(47, "apple");
        classMap.put(48, "sandwich");
        classMap.put(49, "orange");
        classMap.put(50, "broccoli");
        classMap.put(51, "carrot");
        classMap.put(52, "hot dog");
        classMap.put(53, "pizza");
        classMap.put(54, "donut");
        classMap.put(55, "cake");
        classMap.put(56, "chair");
        classMap.put(57, "couch");
        classMap.put(58, "potted plant");
        classMap.put(59, "bed");
        classMap.put(60, "dining table");
        classMap.put(61, "toilet");
        classMap.put(62, "tv");
        classMap.put(63, "laptop");
        classMap.put(64, "mouse");
        classMap.put(65, "remote");
        classMap.put(66, "keyboard");
        classMap.put(67, "cell phone");
        classMap.put(68, "microwave");
        classMap.put(69, "oven");
        classMap.put(70, "toaster");
        classMap.put(71, "sink");
        classMap.put(72, "refrigerator");
        classMap.put(73, "book");
        classMap.put(74, "clock");
        classMap.put(75, "vase");
        classMap.put(76, "scissors");
        classMap.put(77, "teddy bear");
        classMap.put(78, "hair drier");
        classMap.put(79, "toothbrush");
        
        return classMap.get(num);
    }
}
